import React, { useEffect, useMemo, useState } from "react";

import {
  BrowserRouter,
  Link,
  Route,
  Routes,
  useLocation,
  useNavigate,
  useParams,
  useSearchParams
} from "react-router-dom";

import {
  ArrowLeft,
  ArrowRight,
  BookOpen,
  Bookmark,
  BookmarkCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Download,
  ExternalLink,
  Filter,
  Grid2X2,
  Heart,
  History,
  Home,
  Info,
  List,
  Menu,
  Moon,
  Search,
  Share2,
  SlidersHorizontal,
  Sparkles,
  Sun,
  X,
  ZoomIn,
  ZoomOut
} from "lucide-react";

import { jsPDF } from "jspdf";

import { BOOKS, COLLECTIONS, GENRES } from "./data";

function useShelf() {
  const [shelf, setShelf] = useState(() => {
    try {
      return JSON.parse(localStorage.getItem("book-bank-shelf")) || [];
    } catch {
      return [];
    }
  });

  useEffect(() => {
    localStorage.setItem("book-bank-shelf", JSON.stringify(shelf));
  }, [shelf]);

  function toggle(id) {
    setShelf((current) =>
      current.includes(id)
        ? current.filter((item) => item !== id)
        : [...current, id]
    );
  }

  return {
    shelf,
    toggle,
    has: (id) => shelf.includes(id)
  };
}

function useTheme() {
  const [dark, setDark] = useState(() => {
    return localStorage.getItem("book-bank-theme") !== "light";
  });

  useEffect(() => {
    document.documentElement.dataset.theme = dark ? "dark" : "light";
    localStorage.setItem("book-bank-theme", dark ? "dark" : "light");
  }, [dark]);

  return [dark, setDark];
}

function createPdf(book) {
  const pdf = new jsPDF();

  pdf.setFillColor(17, 24, 39);
  pdf.rect(0, 0, 210, 297, "F");

  pdf.setTextColor(231, 215, 173);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(28);

  pdf.text("BOOK BANK", 20, 35);

  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(22);

  const titleLines = pdf.splitTextToSize(book.title, 165);

  pdf.text(titleLines, 20, 75);

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(13);

  pdf.setTextColor(190, 198, 210);

  pdf.text(`By ${book.author}`, 20, 110);
  pdf.text(`${book.genre} · ${book.year}`, 20, 120);
  pdf.text(`${book.pageCount} pages · ${book.language}`, 20, 130);

  pdf.setDrawColor(231, 215, 173);
  pdf.line(20, 145, 190, 145);

  pdf.setFontSize(11);
  pdf.setTextColor(220, 225, 230);

  const description = pdf.splitTextToSize(
    book.description +
      " This digital reading edition is generated by the Book Bank application as a reliable fallback document. The catalog record is provided for educational and discovery purposes.",
    165
  );

  pdf.text(description, 20, 165);

  pdf.setFontSize(10);
  pdf.setTextColor(150, 160, 175);

  pdf.text(
    "Book Bank digital library · Generated reading edition",
    20,
    275
  );

  pdf.text(`Catalog ID: ${book.id}`, 20, 283);

  return pdf;
}

function downloadPdf(book) {
  const pdf = createPdf(book);
  pdf.save(`${book.title.replace(/[^a-z0-9]+/gi, "-")}.pdf`);
}

function pdfUrl(book) {
  const pdf = createPdf(book);
  const blob = pdf.output("blob");
  return URL.createObjectURL(blob);
}

function Header({ dark, setDark, shelfCount }) {
  const [open, setOpen] = useState(false);
  const navigate = useNavigate();

  return (
    <header className="site-header">
      <div className="nav-container">
        <Link to="/" className="brand" onClick={() => setOpen(false)}>
          <span className="brand-mark">
            <BookOpen size={20} />
          </span>

          <span>
            <strong>BOOK</strong> BANK
          </span>
        </Link>

        <nav className={`desktop-nav ${open ? "mobile-open" : ""}`}>
          <Link to="/" onClick={() => setOpen(false)}>
            Home
          </Link>

          <Link to="/catalog" onClick={() => setOpen(false)}>
            Browse
          </Link>

          <Link to="/collections" onClick={() => setOpen(false)}>
            Collections
          </Link>

          <Link to="/shelf" onClick={() => setOpen(false)}>
            My Shelf
            {shelfCount > 0 && (
              <span className="nav-count">{shelfCount}</span>
            )}
          </Link>

          <Link to="/about" onClick={() => setOpen(false)}>
            About
          </Link>
        </nav>

        <div className="nav-actions">
          <button
            className="icon-button"
            aria-label="Search"
            onClick={() => navigate("/catalog")}
          >
            <Search size={19} />
          </button>

          <button
            className="icon-button"
            aria-label="Toggle theme"
            onClick={() => setDark((value) => !value)}
          >
            {dark ? <Sun size={19} /> : <Moon size={19} />}
          </button>

          <button
            className="mobile-menu"
            aria-label="Open menu"
            onClick={() => setOpen((value) => !value)}
          >
            {open ? <X /> : <Menu />}
          </button>
        </div>
      </div>
    </header>
  );
}

function Footer() {
  return (
    <footer className="footer">
      <div className="footer-inner">
        <div>
          <div className="brand footer-brand">
            <span className="brand-mark">
              <BookOpen size={18} />
            </span>
            <span>
              <strong>BOOK</strong> BANK
            </span>
          </div>

          <p className="footer-copy">
            A quiet place for curious minds.
          </p>
        </div>

        <div className="footer-links">
          <div>
            <h4>Explore</h4>
            <Link to="/catalog">Catalog</Link>
            <Link to="/collections">Collections</Link>
            <Link to="/shelf">My Shelf</Link>
          </div>

          <div>
            <h4>Information</h4>
            <Link to="/about">About</Link>
            <a href="mailto:hello@bookbank.example">Contact</a>
            <a href="#">Privacy</a>
          </div>

          <div>
            <h4>Library</h4>
            <span>100+ titles</span>
            <span>Multiple genres</span>
            <span>Browser reading</span>
          </div>
        </div>
      </div>

      <div className="footer-bottom">
        <span>© 2026 Book Bank</span>
        <span>Built for readers.</span>
      </div>
    </footer>
  );
}

function Layout({ children, dark, setDark, shelfCount }) {
  return (
    <>
      <Header
        dark={dark}
        setDark={setDark}
        shelfCount={shelfCount}
      />

      <main>{children}</main>

      <Footer />
    </>
  );
}

function BookCover({ book, large = false }) {
  return (
    <div
      className={`book-cover ${large ? "large" : ""}`}
      style={{
        "--cover": book.coverColor
      }}
    >
      <div className="cover-noise" />

      <div className="cover-top">
        BOOK BANK
      </div>

      <div className="cover-letter">
        {book.coverArt}
      </div>

      <div className="cover-title">
        {book.title}
      </div>

      <div className="cover-author">
        {book.author}
      </div>

      <div className="cover-year">
        {book.year < 0 ? `${Math.abs(book.year)} BCE` : book.year}
      </div>
    </div>
  );
}

function Rating({ value }) {
  return (
    <span className="rating">
      <span className="stars">★★★★★</span>
      <span>{value}</span>
    </span>
  );
}

function BookCard({ book, shelf, toggleShelf, list = false }) {
  return (
    <article className={`book-card ${list ? "book-list-card" : ""}`}>
      <Link to={`/book/${book.id}`} className="cover-link">
        <BookCover book={book} />
      </Link>

      <div className="book-card-content">
        <div className="book-meta-top">
          <span>{book.genre}</span>
          <span>{book.year}</span>
        </div>

        <Link to={`/book/${book.id}`} className="book-title">
          {book.title}
        </Link>

        <div className="book-author">
          {book.author}
        </div>

        <div className="book-card-bottom">
          <Rating value={book.rating} />

          <button
            className={`mini-action ${
              shelf.has(book.id) ? "saved" : ""
            }`}
            onClick={() => toggleShelf(book.id)}
            aria-label={
              shelf.has(book.id)
                ? "Remove from shelf"
                : "Add to shelf"
            }
          >
            {shelf.has(book.id) ? (
              <BookmarkCheck size={17} />
            ) : (
              <Bookmark size={17} />
            )}
          </button>
        </div>
      </div>
    </article>
  );
}

function SectionHeading({
  eyebrow,
  title,
  description,
  action
}) {
  return (
    <div className="section-heading">
      <div>
        {eyebrow && <div className="eyebrow">{eyebrow}</div>}
        <h2>{title}</h2>
        {description && <p>{description}</p>}
      </div>

      {action}
    </div>
  );
}

function Home({ shelf, toggleShelf }) {
  const featured = BOOKS.filter((book) => book.featured).slice(0, 6);

  return (
    <div>
      <section className="hero">
        <div className="hero-glow glow-one" />
        <div className="hero-glow glow-two" />

        <div className="hero-inner">
          <div className="hero-copy">
            <div className="eyebrow">
              <Sparkles size={14} />
              THE DIGITAL BOOK BANK
            </div>

            <h1>
              Knowledge,
              <br />
              <em>beautifully</em> kept.
            </h1>

            <p>
              Discover a growing digital library of influential
              books. Search, save and read directly in your
              browser.
            </p>

            <div className="hero-actions">
              <Link className="button primary" to="/catalog">
                Browse catalog
                <ArrowRight size={18} />
              </Link>

              <Link className="button secondary" to="/collections">
                Explore collections
              </Link>
            </div>

            <div className="hero-search">
              <Search size={20} />

              <input
                placeholder="Search books, authors, ideas..."
                onKeyDown={(event) => {
                  if (event.key === "Enter") {
                    const value = event.target.value.trim();

                    window.location.href = value
                      ? `/catalog?search=${encodeURIComponent(value)}`
                      : "/catalog";
                  }
                }}
              />

              <span>↵</span>
            </div>
          </div>

          <div className="hero-library">
            <div className="library-stack stack-one">
              <BookCover book={featured[0]} />
            </div>

            <div className="library-stack stack-two">
              <BookCover book={featured[1]} />
            </div>

            <div className="library-stack stack-three">
              <BookCover book={featured[2]} />
            </div>

            <div className="hero-card">
              <span>CURATED LIBRARY</span>
              <strong>{BOOKS.length}+</strong>
              <small>titles to explore</small>
            </div>
          </div>
        </div>
      </section>

      <section className="stats-section">
        <div className="stats-grid">
          <div>
            <strong>{BOOKS.length}+</strong>
            <span>Books</span>
          </div>

          <div>
            <strong>{GENRES.length - 1}</strong>
            <span>Genres</span>
          </div>

          <div>
            <strong>
              {Math.round(
                BOOKS.reduce((sum, book) => sum + book.downloads, 0) /
                  1000
              )}
              K+
            </strong>
            <span>Reads & downloads</span>
          </div>

          <div>
            <strong>24/7</strong>
            <span>Browser access</span>
          </div>
        </div>
      </section>

      <section className="content-section">
        <SectionHeading
          eyebrow="HANDPICKED"
          title="Featured books"
          description="A selection of enduring works to begin your journey."
          action={
            <Link to="/catalog" className="text-link">
              View all <ArrowRight size={16} />
            </Link>
          }
        />

        <div className="book-grid featured-grid">
          {featured.map((book) => (
            <BookCard
              key={book.id}
              book={book}
              shelf={shelf}
              toggleShelf={toggleShelf}
            />
          ))}
        </div>
      </section>

      <section className="dark-feature">
        <div className="dark-feature-inner">
          <div>
            <div className="eyebrow">READ WITHOUT FRICTION</div>

            <h2>
              Your library,
              <br />
              wherever curiosity takes you.
            </h2>

            <p>
              Open a title, settle in and read in a distraction-free
              browser reader. Your shelf stays on your device.
            </p>

            <Link className="button cream" to="/catalog">
              Find your next book
              <ArrowRight size={18} />
            </Link>
          </div>

          <div className="feature-orbit">
            <div className="orbit-book">
              <BookOpen size={54} />
            </div>
          </div>
        </div>
      </section>

      <section className="content-section">
        <SectionHeading
          eyebrow="START SOMEWHERE"
          title="Explore by subject"
        />

        <div className="genre-grid">
          {GENRES.filter((genre) => genre !== "All")
            .slice(0, 10)
            .map((genre) => (
              <Link
                key={genre}
                to={`/catalog?genre=${encodeURIComponent(genre)}`}
                className="genre-tile"
              >
                <span>{genre}</span>
                <ArrowRight size={17} />
              </Link>
            ))}
        </div>
      </section>
    </div>
  );
}

function Catalog({ shelf, toggleShelf }) {
  const [params, setParams] = useSearchParams();

  const [search, setSearch] = useState(
    params.get("search") || ""
  );

  const [genre, setGenre] = useState(
    params.get("genre") || "All"
  );

  const [year, setYear] = useState(
    params.get("year") || "All"
  );

  const [language, setLanguage] = useState("All");
  const [rating, setRating] = useState("All");
  const [sort, setSort] = useState("popularity");

  const [list, setList] = useState(false);
  const [page, setPage] = useState(1);

  const pageSize = 18;

  const years = [
    "All",
    "Before 1900",
    "1900–1950",
    "1951–2000",
    "2001+"
  ];

  const filtered = useMemo(() => {
    let result = [...BOOKS];

    const query = search.toLowerCase().trim();

    if (query) {
      result = result.filter(
        (book) =>
          book.title.toLowerCase().includes(query) ||
          book.author.toLowerCase().includes(query) ||
          book.genre.toLowerCase().includes(query) ||
          book.tags.some((tag) =>
            tag.toLowerCase().includes(query)
          )
      );
    }

    if (genre !== "All") {
      result = result.filter((book) => book.genre === genre);
    }

    if (year !== "All") {
      result = result.filter((book) => {
        if (year === "Before 1900") return book.year < 1900;
        if (year === "1900–1950")
          return book.year >= 1900 && book.year <= 1950;
        if (year === "1951–2000")
          return book.year >= 1951 && book.year <= 2000;
        if (year === "2001+") return book.year >= 2001;
        return true;
      });
    }

    if (language !== "All") {
      result = result.filter(
        (book) => book.language === language
      );
    }

    if (rating !== "All") {
      result = result.filter(
        (book) => book.rating >= Number(rating)
      );
    }

    result.sort((a, b) => {
      if (sort === "title")
        return a.title.localeCompare(b.title);

      if (sort === "author")
        return a.author.localeCompare(b.author);

      if (sort === "year")
        return b.year - a.year;

      return b.downloads - a.downloads;
    });

    return result;
  }, [search, genre, year, language, rating, sort]);

  useEffect(() => {
    setParams((current) => {
      if (search) current.set("search", search);
      else current.delete("search");

      if (genre !== "All") current.set("genre", genre);
      else current.delete("genre");

      return current;
    });
  }, [search, genre, setParams]);

  useEffect(() => {
    setPage(1);
  }, [search, genre, year, language, rating, sort]);

  const pages = Math.max(
    1,
    Math.ceil(filtered.length / pageSize)
  );

  const visible = filtered.slice(
    (page - 1) * pageSize,
    page * pageSize
  );

  function clearFilters() {
    setSearch("");
    setGenre("All");
    setYear("All");
    setLanguage("All");
    setRating("All");
    setSort("popularity");
    setPage(1);
  }

  return (
    <div className="page">
      <section className="catalog-head">
        <div>
          <div className="eyebrow">THE COLLECTION</div>

          <h1>Browse the library.</h1>

          <p>
            Search across {BOOKS.length} books spanning literature,
            science, history, philosophy and more.
          </p>
        </div>

        <div className="catalog-count">
          <strong>{filtered.length}</strong>
          <span>matching titles</span>
        </div>
      </section>

      <section className="catalog-toolbar">
        <div className="search-field">
          <Search size={19} />

          <input
            value={search}
            onChange={(event) => setSearch(event.target.value)}
            placeholder="Search title, author or subject..."
          />

          {search && (
            <button
              className="field-clear"
              onClick={() => setSearch("")}
              aria-label="Clear search"
            >
              <X size={17} />
            </button>
          )}
        </div>

        <div className="toolbar-row">
          <div className="filter-controls">
            <div className="select-wrap">
              <SlidersHorizontal size={16} />

              <select
                value={genre}
                onChange={(event) =>
                  setGenre(event.target.value)
                }
              >
                {GENRES.map((item) => (
                  <option key={item}>{item}</option>
                ))}
              </select>
            </div>

            <div className="select-wrap">
              <History size={16} />

              <select
                value={year}
                onChange={(event) =>
                  setYear(event.target.value)
                }
              >
                {years.map((item) => (
                  <option key={item}>{item}</option>
                ))}
              </select>
            </div>

            <div className="select-wrap">
              <select
                value={rating}
                onChange={(event) =>
                  setRating(event.target.value)
                }
              >
                <option value="All">Any rating</option>
                <option value="4.5">4.5+ rating</option>
                <option value="4.7">4.7+ rating</option>
                <option value="4.9">4.9+ rating</option>
              </select>
            </div>

            <button
              className="clear-button"
              onClick={clearFilters}
            >
              Clear filters
            </button>
          </div>

          <div className="view-controls">
            <div className="select-wrap sort-wrap">
              <span>Sort</span>

              <select
                value={sort}
                onChange={(event) =>
                  setSort(event.target.value)
                }
              >
                <option value="popularit
